source 'https://rubygems.org'

# gem 'foundation-rails', git: 'git@github.com:zurb/foundation-rails.git', tag: 'v5.5.1.2'
gem 'foundation-rails', '~> 5.5.1.1' 
gem 'font-awesome-sass'
gem 'rails', '4.2.1'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end